- hosts: network
  roles:
    - network
  tags: setup_network

- hosts: jenkins
  roles:
    - jenkins
  tags: setup_jenkins

- hosts: servers
  roles:
    - servers
  tags: setup_servers
  vars:
    apiserver_ids: []
    webserver_ids: []

- hosts: db
  roles:
    - db
  tags: setup_db

- hosts: apiservers
  roles:
    - apiservers
  tags: setup_apiservers

- hosts: webservers
  roles:
    - webservers
  tags: setup_webservers
