---
- hosts: all
  roles: 
    - common
  tags: common_tasks

- hosts: network
  roles:
    - network
  tags: setup_network

- hosts: infra
  roles:
    - infra
  tags: setup_infra

- hosts: app
  roles:
    - app
  tags: setup_app

- hosts: db
  roles:
    - db
  tags: setup_db
