- hosts: network
  roles:
    - network
  tags: setup_network

- hosts: jenkins
  roles:
    - jenkins
  tags: setup_jenkins

- hosts: servers
  roles:
    - servers
  tags: setup_servers

- hosts: db
  roles:
    - db
  tags: setup_db