- name: Create subnet for AZ1
  ec2_vpc_subnet:
    state: present
    region: "{{ region }}"
    map_public: yes
    vpc_id: "{{ vpc.vpc.id }}"
    cidr: 10.1.0.0/24
    az: "{{ az0 }}"
    tags:
      Name: "{{ prefix }}_az1_subnet"
  register: az1_subnet

- name: Create subnet for AZ2
  ec2_vpc_subnet:
    state: present
    region: "{{ region }}"
    map_public: yes
    vpc_id: "{{ vpc.vpc.id }}"
    cidr: 10.1.1.0/24
    az: "{{ az1 }}"
    tags:
      Name: "{{ prefix }}_az2_subnet"
  register: az2_subnet

- name: Save Subnet details
  blockinfile:
    path: "{{ dynamic_config }}"
    block: |
      az1_subnet_id: "{{ az1_subnet.subnet.id }}"
      az2_subnet_id: "{{ az2_subnet.subnet.id }}"
    create: yes
    marker: "# {mark} ANSIBLE MANAGED BLOCK: Subnets"