- name: Create NAT subnet route table
  ec2_vpc_route_table:
    region: "{{ region }}"
    vpc_id: "{{ vpc.vpc.id }}"
    subnets:
      - "{{ az1_subnet.subnet.id }}"
      - "{{ az2_subnet.subnet.id }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ inet_gw.gateway_id }}"
    tags:
      Name: "{{ prefix }}_route_table"
  register: route_table

- name: Save Route table details
  blockinfile:
    path: "{{ dynamic_config }}"
    block: |
      route_table_id: "{{ route_table.route_table.id }}"
    create: yes
    marker: "# {mark} ANSIBLE MANAGED BLOCK: Route Table"