- name: Create EC2 instance for Jenkins
  ec2:
    region: "{{ region }}"
    key_name: "{{ ssh_keypair_id }}"
    instance_type: "{{ ec2_type }}"
    image: "{{ ec2_ami }}"
    wait: yes
    group_id: "{{ sec_grp.group_id }}"
    vpc_subnet_id: "{{az1_subnet.subnet.id }}"
    assign_public_ip: yes
    count_tag:
      type: jenkins
    exact_count: 1
    instance_tags:
      Name: "{{ prefix }}_jenkins_box"
      type: jenkins
  register: jenkins_box

- debug:
    var: jenkins_box

- name: Save Jenkins box details
  blockinfile:
    path: "{{ dynamic_config }}"
    block: |
      {% if not jenkins_box.instance_ids %}
      {% set ins_id = jenkins_box.tagged_instances[0].id %}
      {% else %}
      {% set ins_id = jenkins_box.instance_ids[0] %}
      {% endif %}
      jenkins_instance_id: "{{ ins_id }}"
    create: yes
    marker: "# {mark} ANSIBLE MANAGED BLOCK: Jenkins"


# - name: Install Java 1.8
