---  
- name: Create VPC, InetGW and SecurityGroup
  include_tasks: 00_create_vpc.yml

- name: Create subnets
  include_tasks: 10_create_subnets.yml

- name: Create route tables
  include_tasks: 20_create_route_tables.yml

- name: Create the Jenkins box
  include_tasks: 30_setup_jenkins.yml

