- name: Create EC2 instance for Web
  ec2:
    region: "{{ region }}"
    key_name: "{{ ssh_keypair_id }}"
    instance_type: "{{ ec2_type }}"
    image: "{{ ec2_ami }}"
    wait: yes
    group_id: "{{ sec_grp_id }}"
    vpc_subnet_id: "{{ vars['az' + item|string + '_subnet_id'] }}"
    assign_public_ip: yes
    exact_count: 1
    count_tag:
      Name: "{{ prefix }}-web{{ item }}"
      type: webserver
    instance_tags:
      Name: "{{ prefix }}-web{{ item }}"
      type: webserver
  with_items:
    - 1
    - 2
  register: webservers

- name: Create EC2 instance for API
  ec2:
    region: "{{ region }}"
    key_name: "{{ ssh_keypair_id }}"
    instance_type: "{{ ec2_type }}"
    image: "{{ ec2_ami }}"
    wait: yes
    group_id: "{{ sec_grp_id }}"
    vpc_subnet_id: "{{ vars['az' + item|string + '_subnet_id'] }}"
    assign_public_ip: yes
    exact_count: 1
    count_tag:
      Name: "{{ prefix }}-api{{ item }}"
      type: apiserver
    instance_tags:
      Name: "{{ prefix }}-api{{ item }}"
      type: apiserver
  with_items:
    - 1
    - 2
  register: apiservers



